version: '3.8'

services:

  mariadb:
    build: ./mariadb
    container_name: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    networks:
      - app-network
    restart: always

  wordpress:
    build: ./wordpress
    container_name: wordpress
    volumes:
      - ./data/wp:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - app-network
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - app-network
    restart: always
    environment:
      - NGINX_HOST=localhost

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/olamrabt/data/db
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/olamrabt/data/wp
      o: bind

networks:
  app-network:
    driver: bridge
