version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - app-network
    restart: always

  wordpress:
    build: ./wordpress
    container_name: wordpress
    volumes:
      - ./data/wp:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - app-network
    restart: always

  mariadb:
    build: ./mariadb
    container_name: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - app-network
    restart: always

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/olamrabt/data/db
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/olamrabt/data/wp
      o: bind

networks:
  app-network:
    driver: bridge