version: '3.8'

services:

  mariadb:
    image: mariadb:olamrabt
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    networks:
      - app-network
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  wordpress:
    image: wordpress:olamrabt
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - DOMAIN_NAME=$DOMAIN_NAME
      - WP_TITLE=$WP_TITLE
      - WP_ADMIN_N=$WP_ADMIN_N
      - WP_ADMIN_P=$WP_ADMIN_P
      - WP_ADMIN_E=$WP_ADMIN_E
      - WP_U_NAME=$WP_U_NAME
      - WP_U_EMAIL=$WP_U_EMAIL
      - WP_U_PASS=$WP_U_PASS
      - WP_U_ROLE=$WP_U_ROLE

  nginx:
    image: nginx:olamrabt
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wp:/var/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - app-network
    restart: always

volumes:
  db:
    driver_opts:
      device: /home/olamrabt/data/db
      type: none
      o: bind
  wp:
    driver_opts:
      device: /home/olamrabt/data/wp
      type: none
      o: bind

networks:
  app-network:
    driver: bridge
